# Generated by Django 3.2.5 on 2021-07-06 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userModel',
        ),
    ]
