# Generated by Django 3.2.5 on 2021-07-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_createpoll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpoll',
            name='options',
            field=models.CharField(max_length=300),
        ),
    ]
