# Generated by Django 3.2.5 on 2021-07-22 05:16

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_remove_createpoll_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpoll',
            name='options',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
