# Generated by Django 3.2.5 on 2021-07-28 13:24

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_alter_createpoll_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpoll',
            name='voters',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
